# Generated by Django 4.2.1 on 2023-05-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('editora', models.CharField(max_length=255)),
                ('ano', models.IntegerField()),
                ('descricao', models.TextField()),
                ('ativo', models.BooleanField()),
                ('imagem', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Livros',
            },
        ),
    ]
